name: aaunal
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - numpy
  - pandas
  - scipy
  - sympy
  - beautifulsoup4
  - pip
  - pip:
    - xxhash==3.4.1
    - xlsxwriter==3.2.0
    - triton==2.3.1
    - torchaudio==2.3.1
    - torch==2.3.1
    - speechrecognition==3.8.1
    - pypdf2==3.0.1
    - pdfplumber==0.11.2
    - nvidia-nvtx-cu12==12.1.105
    - nvidia-nvjitlink-cu12==12.5.82
    - nvidia-nccl-cu12==2.20.5
    - nvidia-cusparse-cu12==12.1.0.106
    - nvidia-cusolver-cu12==11.4.5.107
    - nvidia-curand-cu12==10.3.2.106
    - nvidia-cufft-cu12==11.0.2.54
    - nvidia-cudnn-cu12==8.9.2.26
    - nvidia-cuda-runtime-cu12==12.1.105
    - nvidia-cuda-nvrtc-cu12==12.1.105
    - nvidia-cuda-cupti-cu12==12.1.105
    - nvidia-cublas-cu12==12.1.3.1
    - huggingface-hub==0.24.2
    - extract-msg==0.23.1
    - evaluate==0.4.2
    - ebooklib==0.17.1
    - compressed_rtf==1.0.6
    - tzdata==2024.1
    - setuptools==71.1.0
