#!/bin/bash

for p in /sys/class/infiniband/*/ports/*; do
    [ -e "$p" ] || continue
    p=${p#/sys/class/infiniband/}
    nohup /home/conda/feedstock_root/build_artifacts/rdma-core_1684784914292/_build_env/x86_64-conda-linux-gnu/sysroot/usr/bin/systemctl start "srp_daemon_port@${p/\/ports\//:}" </dev/null >&/dev/null &
done
